const big_deal = 
[{
    id:"realEstateB1",
    name: "8-plex for Sale",
    type: "Real Estate",
    description: "Reinvesting owner offers 8-plex for sale at reasonable price. Financing already in place. All it needs is your down payment.",
    rule: "Use this yourself or sell to another player. 51% ROI, may sell for ₹1,65,00,000 to ₹2,00,00,000.",
    roi: 0.51,
    cost: 16500000,
    downPayment: 3000000,
    mortgage: 13500000,
    cashFlow: 130000,
    tag: "8PLEX",
    landType: "plex",
    units: 8,
},

{
    id: "realEstateB2", 
    name: "House for Sale - 3 Br/2 Ba",
    type: "Real Estate",
    decription: "Divorce leads to sale of this 3/2 house in an area full of owner occupied homes. Has been on the market 5 months.",
    rule: "Use this yourself or sell to another player. 30% ROI, may sell for ₹50,00,000 to ₹1,00,00,000.",
    roi: 0.3,
    cost: 5300000,
    downPayment: 1500000,
    mortgage: 4000000,
    cashFlow: 40000,
    tag: "3Br/2ba",
    landType: "3Br/2Ba",
},
{
    id: "realEstateB3",
    name: "House for Sale - 3 Br/2 Ba",
    type: "Real Estate",
    description: "Good investment potential in this 3/2 house if you can be patient. Positive cash flow even though rents are weak.",
    rule: "Use this yourself or sell to another player. 45% ROI, may sell for ₹50,00,000 to ₹1,00,00,000.",
    roi: 0.45,
    cost: 5000000,
    downPayment: 600000,
    mortgage: 4300000,
    cashFlow: 25000,
    tag: "3Br/2Ba",
    landType: "3Br/2Ba"
},
{
    id: "realEstateB4",
    name: "4-plex for Sale",
    type: "Real Estate",
    description: "4-plex available - forced sale. Out-of-state, financially distressed owner years behind on taxes. Some records available.",
    rule: "Use this yourself or sell to another player. 56% ROI, may sell for ₹8,00,000 to ₹1,00,00,000.",
    roi: 0.56,
    cost: 6000000,
    downPayment: 1200000,
    mortgage: 5000000,
    cashFlow: 55000,
    tag: "4PLEX",
    landType: "plex",
    units: 4
},
{
    id: "realEstateB5",
    name: "8-plex for Sale",
    type: "Real Estate",
    description: "Professional person urgently needs cash to save partnership. 8-plex sale to raise capital, good opportunity for right person.",
    rule: "Use this yourself or sell to another player. 64% ROI, may sell for ₹1,50,00,000 to ₹2,00,00,000.",
    roi: 0.64,
    cost: 1200000,
    downPayment: 2400000,
    mortgage: 9500000,
    cashFlow: 130000,
    tag: "8PLEX",
    landType: "plex",
    units: 8
}/*,
{
    id: "realEstateB6",
    name: "Automated Business for Sale",
    type: "Automated Business",
    description: "Successful 4 bay coin operated auto wash near busy intersection. Seller is moving to retirement community out of state.",
    rule: "Use this yourself or sell to another player. 86% ROI. No other buyers in sight.",
    roi: 0.86,
    cost: 125000,
    downPayment: 25000,
    liability: 100000,
    cashFlow: 1800,
    tag: "CarWash",
    landType: "car wash"
},
{
    id: "realEstateB7",
    name: "20 Acres for Sale",
    type: "Real Estate",
    description: " 20 acres of vacant land, currently zoned residential. Possibly of good appreciation if rezoned commercial.",
    rule: " Use this yourself or sell to another player. 0% ROI, may sell for ??.",
    roi: 0,
    cost: 20000,
    downPayment: 20000,
    mortgage: 0,
    cashFlow: 0,
    tag: "20Acres",
    landType: "20 acres"
},
{
    id: "realEstateB8",
    name: "8-plex for Sale",
    type: "Real Estate",
    description: "Retiring investor/owner offers his 8-plex at current appraisal value. Professional lawn service and management. Full records.",
    rule: "Use this yourself or sell to another player. 29% ROI, may sell for ₹1,50,00,000 to ₹2,00,00,000.",
    roi: 0.29,
    cost: 20000000,
    downPayment: 3000000,
    mortgage: 15000000,
    cashFlow: 70000,
    tag: "8PLEX",
    landType: "plex",
    units: 8
},
 {
    id: "realEstateB9", 
    name: "4-plex for Sale",
    type: "Real Estate",
    description: '"Project" 4-plex for sale in rehabilitating neighborhood. Owner being forced out by income tax liens.',
    rule: "Use this yourself or sell to another player. 24% ROI, may sell for ₹75,00,000 to ₹1,00,00,000.",
    roi: 0.24,
    cost:  6000000,
    downPayment: 1500000,
    mortgage: 4500000,
    cashFlow: 30000,
    tag: "4PLEX",
    landType: "plex",
    units: 4
}*/,
{
    id: "realEstateB10",
    name: "4-plex for Sale",
    type: "Real Estate",
    description: "Older 4-plex next to new highway for sale. Owner/occupant moving to wuieter area. Priced for quick sale.",
    rule: "Use this yourself or sell to another player. 40% ROI, may sell for ₹75,00,000 to ₹1,00,00,000.",
    roi: 0.4,
    cost: 7000000,
    downPayment: 1200000,
    mortgage: 5700000,
    cashFlow: 4000000,
    tag: "4PLEX",
    landType: "plex",
    units: 4
},
{
    id: "realEstateB11",
    name: "Pizza Franchise for Sale",
    type: "Real Estate",
    description: "Healthy-pizza company franchise. Trend in nutritious fast-food booming. Next to college. High Traffic",
    rule: "Use this yourself or sell to another player. 60% ROI, may sell for ₹3,00,00,000 to ₹6,00,00,000.",
    roi: 0.6,
    cost: 30000000,
    downPayment: 7500000,
    mortgage: 30000000,
    cashFlow: 400000,
    tag: "PIZZA",
    landType: "franchise"
},
{
    id: "realEstateB12",
    name: "Duplex for Sale",
    type: "Real Estate",
    description: "Duplex owner must sell to pay hospital bills. Two tenants in place, all records, good investment oppurtunity.",
    rule: "Use this yourself or sell to another player. 40% ROI, may sell for ₹40,00,000 to ₹60,00,000.",
    roi: 0.4,
    cost: 4500000,
    mortgage: 3600000,
    downPayment: 900000,
    cashFlow: 30000,
    tag: "DUPLEX",
    landType: "duplex",
    units: 2
},
{
    id: "realEstateB13",
    name: "Bed & Breakfast for Sale",
    type: "Real Estate",
    description: "Owner retiring, wants out NOW. Great clientele in resort community. 5Br/3Ba.",
    rule: "Use this yourself or sell to another player. 40% ROI, may sell for ₹75,00,000 to ₹2,25,00,000.",
    roi: 0.4,
    cost: 11200000,
    mortgage: 9000000,
    downPayment: 2300000,
    cashFlow: 75000,
    tag: "Bed&Br",
    landType: "bed breakfast"
},
{
    id: "realEstateB14",
    name: "House for Sale - 3 Br/2 Ba",
    type: "Real Estate",
    description: "3/2 house on golf course offers potential capital gain plus current cash flow. Good rentals and nice financing.",
    rule: "Use this yourself or sell to another player. 51% ROI, may sell for ₹50,00,000 to ₹1,00,00,000.",
    roi: 0.51,
    cost: 5600000,
    mortgage: 5000000,
    downPayment: 2500000,
    cashFlow: 150000,
    tag: "3Br/2Ba",
    landType: "3Br/2Ba"
},
{
    id: "realEstateB15",
    name: "Duplex for Sale",
    type: "Real Estate",
    description: "Tenants in place at this investment duplex! Owner has income tax problems, needs to sell quickly.",
    rule: "Use this yourself or sell to another player. 48% ROI, may sell for ₹40,00,000 to ₹6000000.",
    roi: 0.48,
    cost: 3400000,
    mortgage: 3000000,
    downPayment: 600000,
    cashFlow: 24000,
    tag: "DUPLEX",
    landType: "duplex",
    units: 2
},
{
    id: "realEstateB16",
    name: "4-plex for Sale",
    type: "Real Estate",
    description: "4-plex for sale by owner, moving to another state. Full records, fully rented, low occupant turnover in good neighborhood.",
    rule: "Use this yourself or sell to another player. 75% ROI, may sell for ₹100,000 to ₹140,000.",
    roi: 0.75,
    cost: 14000000,
    downPayment: 320000,
    mortgage: 1080000,
    cashFlow: 20000,
    tag: "4PLEX",
    landType: "plex",
    units: 4
},
{
    id: "realEstateB17",
    name: "House for Sale - 3 Br/2 Ba",
    type: "Real Estate",
    description: "Businessman liquidating this 3/2 house, needs cash to save his business. Currently occupied by happy tenant.",
    rule: "Use this yourself or sell to another player. 26% ROI, may sell for ₹65,000 to ₹135,000.",
    roi: 0.26,
    cost: 6500000,
    mortgage: 5800000,
    downPayment: 700000,
    cashFlow: 150000,
    tag: "3Br/2Ba",
    landType: "3Br/2Ba"
},
{
    id: "realEstateB18",
    name: "House for Sale - 3 Br/2 Ba",
    type: "Real Estate",
    description: "Still level 3/2 house on out of way golf course offered by heirs of owner. Gold membership included.",
    rule: "Use this yourself or sell to another player. -12% ROI, may sell for ₹65,000 to ₹150,000.",
    roi: -0.12,
    cost: 115000,
    mortgage: 105000,
    downPayment: 10000,
    cashFlow: -100,
    tag: "3Br/2Ba",
    landType: "3Br/2Ba"
},
{
    id: "realEstateB19",
    name: "House for Sale - 3 Br/2 Ba",
    type: "Real Estate",
    description: "Nice 3/2 house with in ground pool and full appliances available in upper middle class area. Good schools.",
    rule: "Use this yourself or sell to another player. -6% ROI, may sell for ₹65,000 to ₹150,000.",
    roi: -0.12,
    cost: 125000,
    mortgage: 105000,
    downPayment: 20000,
    cashFlow: -10000,
    tag: "3Br/2Ba",
    landType: "3Br/2Ba"
},
{
    id: "realEstateB20",
    name: "Apartment Houses for Sale",
    type: "Real Estate",
    description: "2 buildings totaling 24 units for sale. Owner managed with on-site assistant. Retirement prompts sale.",
    rule: "Use this yourself or sell to another player. 54% ROI, may sell for ₹600,000 to ₹960,000.",
    roi: 0.54,
    cost: 575000,
    mortgage: 500000,
    downPayment: 75000,
    cashFlow: 34000,
    units: 48,
    tag: "2x 24u",
    landType: "apartment",
    units: 48
},

{
    id: "realEstateB21",
    name: "Car Wash for Sale",
    type: "Real Estate",
    description: "Family car wash for sale. Family feuding. Wants out ASAP. Prime location in highgrowth area.",
    rule: "Use this yourself or sell to another player. 36% ROI, may sell for 12-25 times annual cash flow.",
    roi: 0.36,
    cost: 350000,
    mortgage: 300000,
    downPayment: 50000,
    cashFlow: 15000,
    tag: "CarWash",
    landType: "car wash"
},
{
    id: "realEstateB22",
    name: "Apartment House for Sale",
    type: "Real Estate",
    description: "12 unit apartment house offered by out-of-state heirs of handyman/owner. Long waiting list for apartment in this building.",
    rule: "Use this yourself or sell to another player. 58% ROI, may sell for ₹300,000 to ₹480,000.",
    roi: 0.58,
    cost: 350000,
    mortgage: 300000,
    downPayment: 50000,
    cashFlow: 24000,
    units: 12,
    tag: "12Unit",
    landType: "apartment"
},
{
    id: "realEstateB23",
    name: "4-plex for Sale",
    type: "Real Estate",
    description: "Nice, well maintained 4-plex in good neighborhood. Stable tenants, positive cash flow, few problems. Full records.",
    rule: "Use this yourself or sell to another player. 48% ROI, may sell for ₹100,000 to ₹140,000.",
    roi: 0.48,
    cost: 12500000,
    downPayment: 1500000,
    mortgage: 11000000,
    cashFlow: 60000,
    tag: "4PLEX",
    landType: "plex",
    units: 4
},
{
    id: "realEstateB24",
    name: "Apartment House for Sale",
    type: "Real Estate",
    description: "60 unit complex available from pension fund that foreclosed on builder/owner. On-site management in place.",
    rule: "Use this yourself or sell to another player. 66% ROI, may sell for ₹1,500,000 to ₹2,700,000.",
    roi: 0.66,
    cost: 1200000,
    mortgage: 1000000,
    downPayment: 200000,
    cashFlow: 20000,
    units: 60,
    tag: "60Unit",
    landType: "apartment"
},
{
    id: "realEstateB25",
    name: "Duplex for Sale",
    type: "Real Estate",
    description: "This duplex is the best in the neighborhood! Proud owner retiring to another state to be near her grandchildren.",
    rule: "Use this yourself or sell to another player. 24% ROI, may sell for ₹50,000 to ₹80,000.",
    roi: 0.24,
    cost: 7000000,
    mortgage: 6300000,
    downPayment: 770000,
    cashFlow: 140000,
    tag: "DUPLEX",
    landType: "duplex",
    units: 2
},
{
    id: "realEstateB26",
    name: "Small Shopping Mall for Sale",
    type: "Real Estate",
    description: "Bank has taken back mall from bankrupt owner. Mall is currently 50% occupied. Just listed today.",
    rule: "Use this yourself or sell to another player. 19% ROI, may sell for ₹35,000 to ₹150,000.",
    roi: 0.19,
    cost: 500000,
    mortgage: 0,
    downPayment: 50000,
    cashFlow: 8000,
    tag: "MALL",
    landType: "mall"
},
{
    id: "realEstateB27",
    name: "Apartment House for Sale",
    type: "Real Estate",
    description: "24 unit older building near community college available from retiring owner/builder. Fully rented, nice cash flow.",
    rule: "Use this yourself or sell to another player. 67% ROI, may sell for ₹600,000 to ₹960,000.",
    roi: 0.67,
    cost: 550000,
    mortgage: 500000,
    downPayment: 50000,
    cashFlow: 28000,
    units: 24,
    tag: "24Unit",
    landType: "apartment"
},

{
    id: "realEstateB28",
    name: "Duplex for Sale",
    type: "Real Estate",
    description: "Well maintained duplex in desirable area available due to transfer of owner. Excellent investment opportunity for right buyer.",
    rule: "Use this yourself or sell to another player. 60% ROI, may sell for ₹50,000 to ₹80,000.",
    roi: 0.6,
    cost: 60000,
    mortgage: 54000,
    downPayment: 6000,
    cashFlow: 3000,
    tag: "DUPLEX",
    landType: "duplex",
    units: 2
},

{
    id: "realEstateB29",
    name: "House for Sale - 3 Br/2 Ba",
    type: "Real Estate",
    description: "Downsized manager must sell this 3/2 house, cannot afford payments on new salary. Area in transition.",
    rule: "Use this yourself or sell to another player. 40% ROI, may sell for ₹65,000 to ₹135,000.",
    roi: 0.4,
    cost: 70000,
    mortgage: 61000,
    downPayment: 9000,
    cashFlow: 3000,
    tag: "3Br/2Ba",
    landType: "3Br/2Ba"
},

{
    id: "realEstateB30",
    name: "4-plex for Sale",
    type: "Real Estate",
    description: "4-plex in recovering neighborhood. Fully rented repairs kept up. Needs your down payment and patience.",
    rule: "Use this yourself or sell to another player. 48% ROI, may sell for ₹100,000 to ₹140,000.",
    roi: 0.48,
    cost: 1000000,
    downPayment: 200000,
    mortgage: 800000,
    cashFlow: 8000,
    tag: "4PLEX",
    landType: "4-plex",
    units: 4
},

{
    id: "realEstateB31",
    name: "House for Sale - 3 Br/2 Ba",
    type: "Real Estate",
    description: "Transferred skilled tradesman kept this 3/2 house in excellent condition, so it commands top dollar rentals in older neighborhood.",
    rule: "Use this yourself or sell to another player. 40% ROI, may sell for ₹65,000 to ₹135,000.",
    roi: 0.4,
    cost: 6700000,
    mortgage: 5501000,
    downPayment: 120000,
    cashFlow: 40000,
    tag: "3Br/2Ba",
    landType: "3Br/2Ba"
},

{
    id: "realEstateB32",
    name: "8-plex for Sale",
    type: "Real Estate",
    description: "Owner's legal troubles lead to forced sale of this 8-plex. No qualifying on this loan, as mortgage holder is cooperating.",
    rule: "Use this yourself or sell to another player. 48% ROI, may sell for ₹200,000 to ₹280,000.",
    roi: 0.48,
    cost: 200000,
    downPayment: 40000,
    mortgage: 160000,
    cashFlow: 1600,
    tag: "8PLEX",
    landType: "plex",
    units: 8
},

{
    id: "realEstateB33",
    name: "Duplex for Sale",
    type: "Real Estate",
    description: "Owner moving out of this duplex due to growing family. Tenant remains, well maintained, excellent landscaping.",
    rule: "Use this yourself or sell to another player. 36% ROI, may sell for ₹50,000 to ₹70,000.",
    roi: 0.36,
    cost: 50000,
    mortgage: 42000,
    downPayment: 8000,
    cashFlow: 2400,
    tag: "DUPLEX",
    landType: "duplex",
    units: 2
},

{
    id: "realEstateB34",
    name: "Mansion for Sale - 5 Br/4 Ba",
    type: "Real Estate",
    description: "5/4.5 house outside of metropolitan area offers potential capital gain plus current cash flow. Good rentals and nice financing.",
    rule: "Use this yourself or sell to another player. 51% ROI, may sell for ₹650,000 to ₹1,350,000.",
    roi: 0.51,
    cost: 820000,
    mortgage: 750000,
    downPayment: 80000,
    cashFlow: 10000,
    tag: "5Br/4Ba",
    landType: "5Br/4Ba"
},
{
    id: "realEstateB35",
    name: "Mansion for Sale - 6 Br/6 Ba",
    type: "Real Estate",
    description: "6/6 house in exclusive hollywood neighborhood offers potential capital gain plus current cash flow. Good rentals and nice financing.",
    rule: "Use this yourself or sell to another player. 51% ROI, may sell for ₹6,500,000 to ₹12,150,000.",
    roi: 0.51,
    cost: 11000000,
    mortgage: 8000000,
    downPayment: 3000000,
    cashFlow: 55000,
    tag: "6Br/6Ba",
    landType: "6Br/6Ba"
},
{
    id: "limitedPartnershipB1",
    name: "Limited Partner Wanted",
    type: "Limited Partnership",
    description: "Non-franchise sandwich shop doubling the number of locations. Owner needs additional equity capital to get operating loan.",
    rule: "Use this yourself or sell to another player. 60% ROI, owner may buy you out for ₹60,000 to ₹90,000.",
    roi: 0.6,
    cost: 30000,
    downPayment: 30000,
    liability: 0,
    cashFlow: 15000,
    tag: "LP-Food",
    landType: "limited"
},

{
    id: "limitedPartnershipB2",
    name: "Limited Partner Wanted",
    type: "Limited Partnership",
    description: "Auto Dealer wants to expand into leasing 2 and 3 year old cars. Needs capital as car maker's finance company is not interested.",
    rule: "Use this yourself or sell to another player. 40% ROI, owner may buy you out for ₹60,000 to ₹90,000.",
    roi: 0.4,
    cost: 30000,
    downPayment: 30000,
    liability: 0,
    cashFlow: 10000,
    tag: "LP-Auto",
    landType: "limited"
},
 {
    id: "limitedPartnershipB3",
    name: "Limited Partner Wanted",
    type: "Limited Partnership",
    description: "Successful doctor expanding office and clinic. Needs partner to fund equity portion of construction costs.",
    rule: "Use this yourself or sell to another player. 48% ROI, owner may buy you out for ₹50,000 to ₹75,000.",
    roi: 0.48,
    cost: 25000,
    downPayment: 25000,
    liability: 0,
    cashFlow: 10000,
    tag: "LP-MDOffice",
    landType: "limited"
},
{
    id: "limitedPartnershipB4",
    name: "Limited Partner Wanted",
    type: "Limited Partnership",
    description: "Successful pizza chain expanding into production of frozen pizzas for grocercy stores. Owner needs capital for equipment.",
    rule: "Use this yourself or sell to another player. 48% ROI, owner may buy you out for ₹40,000 to ₹60,000.",
    roi: 0.48,
    cost: 20000,
    downPayment: 20000,
    liability: 0,
    cashFlow: 8000,
    tag: "LP-PIZZA",
    landType: "limited"
},
/*automatedBusinessB1 {
    name: "Automated Business for Sale",
    type: "Automated Business",
    description: "30 video/pinball machines at long term contract locations for sale by overextended owner. Owner is desperate.",
    rule: "Use this yourself or sell to another player. 96% ROI. No other buyers in sight.",
    roi: 0.96,
    cost: 100000,
    downPayment: 20000,
    liability: 80000,
    cashFlow: 1600,
    tag: "PINBALL",
    landType: "business"
},
automatedBusinessB2 {
    name: "Automated Business for Sale",
    type: "Automated Business",
    description: "Successful coin telephone business available due to death of owner. Heirs live out of state. All locations on long term contract.",
    rule: "Use this yourself or sell to another player. 81% ROI. No other buyers in sight.",
    roi: 0.81,
    cost: 200000,
    downPayment: 40000,
    liability: 160000,
    cashFlow: 2700,
    tag: "TELE",
    landType: "business"
},
automatedBusinessB3: {
    name: "Automated Business for Sale",
    type: "Automated Business",
    description: "Personal bankruptcy sale of busy, successful laundromat on busy highway. Absentee owner, contract cleaning.",
    rule: "Use this yourself or sell to another player. 81% ROI. No other buyers in sight.",
    roi: 1,
    cost: 150000,
    downPayment: 30000,
    liability: 120000,
    cashFlow: 2500,
    tag: "LAUNDRY",
    landType: "business"
},

{
    id : "propertyDamage1",
    name: "Sewer Line Breaks",
    type: "Property Damage",
    description: "Water everywhere at your 8-plex! Broken sewer line needs repair immediately. <br> If you own an 8-plex, pay ₹2,000 for new line. (Bank loan available on usual terms.)",
    rule: "If you own more than one 8-plex, pay repairs on only one.",
    propertyType: "8-plex",
    cost: 2000
},
{
    id: "propertyDamage2",
    name: "Tenant Damages Your Property",
    type: "Property Damage",
    description: "Tenant refuses to pay rent after losing job. When you get him evicted you discover significant damages to your property. <br> Insurance covers most damages and costs, but you still are out of pocket ₹1,000. Pay ₹1,000",
    rule: "Pay ₹1,000 if you own any rental real estate",
    propertyType: "rental",
    cost: 1000,
}*/
];
export default big_deal;