const small_deal = [
        {
            id : "mutual01",
            type: "Mutual Fund",
            name: "GRO4US Fund",
            description: "Lower interest rates drive market and fund to strong showing.",
            rule: "Only you may buy as many units as you want at this price. Everyone may sell at this price",
            symbol: "GRO4US",
            price: 2000,
            range: "₹800 to ₹2000",
            dividend: false,
            shares_P1: 0,
            shares_P2: 0,
        },
        {
            id: "mutual02",
            type: "Mutual Fund",
            name: "GRO4US Fund",
            description: "Brilliant young fund manager. Everyone believes he has the Midas touch",
            rule: "Only you may buy as many units as you want at this price. Everyone may sell at this price",
            symbol: "GRO4US",
            price: 1500,
            range: "₹800 to ₹2000",
            dividend: false,
            shares_P1: 0,
            shares_P2: 0,
        },
        {
            id: "mutual03",
            type: "Mutual Fund",
            name: "GRO4US Fund",
            description: "Weak earnings by most companies lead to weak price of mutual fund",
            rule: "Only you may buy as many units as you want at this price. Everyone may sell at this price",
            symbol: "GRO4US",
            price: 800,
            range: "₹800 to ₹2000",
            dividend: false,
            shares_P1: 0,
            shares_P2: 0,
        },
        {
            id: "mutual04",
            type: "Mutual Fund",
            name: "GRO4US Fund",
            description: "Lower interest rates drive market and fund to strong showing.",
            rule: "Only you may buy as many units as you want at this price. Everyone may sell at this price",
            symbol: "GRO4US",
            price: 400,
            range: "₹800 to ₹2000",
            dividend: false,
            shares_P1: 0,
            shares_P2: 0,
        },
        {
            id: "mutual05",
            type: "Mutual Fund",
            name: "GRO4US Fund",
            description: "Powerhouse market drives strong fund's price up to record high",
            rule: "Only you may buy as many units as you want at this price. Everyone may sell at this price",
            symbol: "GRO4US",
            price: 3000,
            range: "₹800 to ₹2000",
            dividend: false,
            shares_P1: 0,
            shares_P2: 0,
        },
        {
            id: "stock001",
            type: "Stock",
            name: "MYT4U Electronics Co.",
            description: "Booming market leads to record share price of this home electronics seller!",
            rule: "Only you may buy as many shares as you want at this price. Everyone may sell at this price.",
            symbol: "MYT4U",
            price: 3000,
            range: "₹400 to ₹2000",
            dividend: false,
            shares_P1: 0,
            shares_P2: 0,
        },
        {
            id: "stock002",
            type: "Stock",
            name: "MYT4U Electronics Co.",
            description: "High inflation leads to poor share price for this home electronics seller.",
            rule: "Only you may buy as many shares as you want at this price. Everyone may sell at this price.",
            symbol: "MYT4U",
            price: 400,
            range: "₹400 to ₹2000",
            dividend: false,
            shares_P1: 0,
            shares_P2: 0,
        },
        {
            id: "stock003",
            type: "Stock",
            name: "MYT4U Electronics Co.",
            description: "Record interest rates lead to substandard share price for this home electronics seller",
            rule: "Only you may buy as many shares as you want at this price. Everyone may sell at this price.",
            symbol: "MYT4U",
            price: 400,
            range: "₹400 to ₹2000",
            dividend: false,
            shares_P1: 0,
            shares_P2: 0,
        },
        {
            id: "stock004",
            type: "Stock",
            name: "MYT4U Electronics Co.",
            description: "Strong market leads to strong share price for this home electronics seller",
            rule: "Only you may buy as many shares as you want at this price. Everyone may sell at this price.",
            symbol: "MYT4U",
            price: 2000,
            range: "₹400 to ₹2000",
            dividend: false,
            shares_P1: 0,
            shares_P2: 0,
        },
        {
            id: "stock005",
            type: "Stock",
            name: "MYT4U Electronics Co.",
            description: "Trade war panic leads to record low share price for this home electronics seller.",
            rule: "Only you may buy as many shares as you want at this price. Everyone may sell at this price.",
            symbol: "MYT4U",
            price: 70,
            range: "₹400 to ₹2000",
            dividend: false,
            shares_P1: 0,
            shares_P2: 0,
        },
        {
            id: "stock006",
            type: "Stock",
            name: "MYT4U Electronics Co.",
            description: "Weak market leads to sagging share price for this home electronics seller.",
            rule: "Only you may buy as many shares as you want at this price. Everyone may sell at this price.",
            symbol: "MYT4U",
            price: 800,
            range: "₹400 to ₹2000",
            dividend: false,
            shares_P1: 0,
            shares_P2: 0,
        },
        {
            id: "stock007",
            type: "Stock",
            name: "MYT4U Electronics Co.",
            description: "Fast growing seller of home electronics headed by 32 year old Harvard grad.",
            rule: "Only you may buy as many shares as you want at this price. Everyone may sell at this price.",
            symbol: "MYT4U",
            price: 1500,
            range: "₹400 to ₹2000",
            dividend: false,
            shares_P1: 0,
            shares_P2: 0,
        },
        {
            id: "stock008",
            type: "Stock",
            name: "MYT4U Electronics Co.",
            description: "Low interest rates lead to substantial share price for this home electronics seller.",
            rule: "Only you may buy as many shares as you want at this price. Everyone may sell at this price.",
            symbol: "MYT4U",
            price: 2000,
            range: "₹400 to ₹2000",
            dividend: false,
            shares_P1: 0,
            shares_P2: 0,
      },
        {
            id: "stock009",
            type: "Stock",
            name: "OK4U Drug Co.",
            description: "Market strength leads to high share price for this long time maker of medicines.",
            rule: "Only you may buy as many shares as you want at this price. Everyone may sell at this price.",
            symbol: "OK4U",
            price: 800,
            range: "₹400 to ₹2000",
            dividend: false,
            shares_P1: 0,
            shares_P2: 0,
        },
        {
            id: "stock0800",
            type: "Stock",
            name: "OK4U Drug Co.",
            description: "Low inflation leads to high share price for this long time maker of medicines.",
            rule: "Only you may buy as many shares as you want at this price. Everyone may sell at this price.",
            symbol: "OK4U",
            price: 1500,
            range: "₹400 to ₹2000",
            dividend: false,
            shares_P1: 0,
            shares_P2: 0,
        },
        {
            id: "stock011",
            type: "Stock",
            name: "OK4U Drug Co.",
            description: "Booming market raises share price of this long time maker of medicines.",
            rule: "Only you may buy as many shares as you want at this price. Everyone may sell at this price.",
            symbol: "OK4U",
            price: 2000,
            range: "₹400 to ₹2000",
            dividend: false,
            shares_P1: 0,
            shares_P2: 0,
        },
        {
            id: "stock012",
            type: "Stock",
            name: "OK4U Drug Co.",
            description: "Interest rates cripple share price of this long time maker of medicines.",
            rule: "Only you may buy as many shares as you want at this price. Everyone may sell at this price.",
            symbol: "OK4U",
            price: 400,
            range: "₹400 to ₹2000",
            dividend: false,
            shares_P1: 0,
            shares_P2: 0,
        },
        {
            id: "stock013",
            type: "Stock",
            name: "OK4U Drug Co.",
            description: "High interest rates cause poor share price of this long time make of medicines.",
            rule: "Only you may buy as many shares as you want at this price. Everyone may sell at this price.",
            symbol: "OK4U",
            price: 800,
            range: "₹400 to ₹2000",
            dividend: false,
            shares_P1: 0,
            shares_P2: 0,
        },
        {
            id: "stock014",
            type: "Stock",
            name: "OK4U Drug Co.",
            description: "Inflation worries cause poor share price of this long time maker of medicines.",
            rule: "Only you may buy as many shares as you want at this price. Everyone may sell at this price.",
            symbol: "OK4U",
            price: 800,
            range: "₹400 to ₹2000",
            dividend: false,
            shares_P1: 0,
            shares_P2: 0,
        },
        {
            id: "stock015",
            type: "Stock",
            name: "OK4U Drug Co.",
            description: "Market panic causes crash in the shares of this long time maker of medicines.",
            rule: "Only you may buy as many shares as you want at this price. Everyone may sell at this price.",
            symbol: "OK4U",
            price: 75,
            range: "₹400 to ₹2000",
            dividend: false,
            shares_P1: 0,
            shares_P2: 0,
        },
        {
            id: "stock016",
            type: "Stock",
            name: "OK4U Drug Co.",
            description: "Long time maker of medicines; especially drugs for people of 70.",
            rule: "Only you may buy as many shares as you want at this price. Everyone may sell at this price.",
            symbol: "OK4U",
            price: 2000,
            range: "₹400 to ₹2000",
            dividend: false,
            shares_P1: 0,
            shares_P2: 0,
        },
        {
            id: "stock021",
            type: "Stock",
            name: "ON2U Entertainment Co.",
            description: "Box office hit by children's division casuses record share price.",
            rule: "Only you may buy as many shares as you want at this price. Everyone may sell at this price.",
            symbol: "ON2U",
            price: 800,
            range: "₹400 to ₹2000",
            dividend: false,
            shares_P1: 0,
            shares_P2: 0,
        },
        {
            id: "stock022",
            type: "Stock",
            name: "ON2U Entertainment Co.",
            description: "Strong demand for company's library of old movies on video leads to good share price.",
            rule: "Only you may buy as many shares as you want at this price. Everyone may sell at this price.",
            symbol: "ON2U",
            price: 2000,
            range: "₹400 to ₹2000",
            dividend: false,
            shares_P1: 0,
            shares_P2: 0,
        },
        {
            id: "stock023",
            type: "Stock",
            name: "ON2U Entertainment Co.",
            description: "New director of movie acquisitions brings revived prospects for share price.",
            rule: "Only you may buy as many shares as you want at this price. Everyone may sell at this price.",
            symbol: "ON2U",
            price: 1500,
            range: "₹400 to ₹2000",
            dividend: false,
            shares_P1: 0,
            shares_P2: 0,
        },
        {
            id: "stock024",
            type: "Stock",
            name: "ON2U Entertainment Co.",
            description: "Movie buyer fired after third mega-flop! Shares sink. Chairman's bonus canceled.",
            rule: "Only you may buy as many shares as you want at this price. Everyone may sell at this price.",
            symbol: "ON2U",
            price: 400,
            range: "₹400 to ₹2000",
            dividend: false,
            shares_P1: 0,
            shares_P2: 0,
        },
        {
            id: "stock025",
            type: "Stock",
            name: "ON2U Entertainment Co.",
            description: "Box office smash hit in adult division causes strong share price.",
            rule: "Only you may buy as many shares as you want at this price. Everyone may sell at this price.",
            symbol: "ON2U",
            price: 2000,
            range: "₹400 to ₹2000",
            dividend: false,
            shares_P1: 0,
            shares_P2: 0,
        },
        {
            id: "stock026",
            type: "Stock",
            name: "ON2U Entertainment Co.",
            description: "Recent merger strengthened market share of this leading company with good outlook.",
            rule: "Only you may buy as many shares as you want at this price. Everyone may sell at this price.",
            symbol: "ON2U",
            price: 1700,
            range: "₹400 to ₹2000",
            dividend: false,
            shares_P1: 0,
            shares_P2: 0,
        },
        {
            id: "stock027",
            type: "Stock",
            name: "ON2U Entertainment Co.",
            description: "Newest theme park loses record amount. Share price hits all-time low.",
            rule: "Only you may buy as many shares as you want at this price. Everyone may sell at this price.",
            symbol: "ON2U",
            price: 75,
            range: "₹400 to ₹2000",
            dividend: false,
            shares_P1: 0,
            shares_P2: 0,
        },
        {
            id: "stock028",
            type: "Stock",
            name: "ON2U Entertainment Co.",
            description: "Box office flop by musical extravaganza in core division causes poor share price.",
            rule: "Only you may buy as many shares as you want at this price. Everyone may sell at this price.",
            symbol: "ON2U",
            price: 800,
            range: "₹400 to ₹2000",
            dividend: false,
            shares_P1: 0,
            shares_P2: 0,
        }
];

export default small_deal;