const small_deal = [
        {
            id : "mutual010",
            type: "Mutual Fund",
            name: "GRO4US Fund",
            description: "Lower interest rates drive market and fund to strong showing.",
            rule: "Only you may buy as many units as you want at this price. Everyone may sell at this price",
            symbol: "GRO4US",
            price: 30,
            range: "$10 to $30",
            dividend: false,
            id: "gro4us30",
            shares: 0
        },
        {
            id: "mutual02",
            type: "Mutual Fund",
            name: "GRO4US Fund",
            description: "Brilliant young fund manager. Everyone believes he has the Midas touch",
            rule: "Only you may buy as many units as you want at this price. Everyone may sell at this price",
            symbol: "GRO4US",
            price: 20,
            range: "$10 to $30",
            dividend: false,
            id: "gro4us20",
            shares: 0
        },
        {
            id: "mutual03",
            type: "Mutual Fund",
            name: "GRO4US Fund",
            description: "Weak earnings by most companies lead to weak price of mutual fund",
            rule: "Only you may buy as many units as you want at this price. Everyone may sell at this price",
            symbol: "GRO4US",
            price: 10,
            range: "$10 to $30",
            dividend: false,
            id: "gro4us10",
            shares: 0
        },
        {
            id: "mutual04",
            type: "Mutual Fund",
            name: "GRO4US Fund",
            description: "Lower interest rates drive market and fund to strong showing.",
            rule: "Only you may buy as many units as you want at this price. Everyone may sell at this price",
            symbol: "GRO4US",
            price: 5,
            range: "$10 to $30",
            dividend: false,
            id: "gro4us05",
            shares: 0
        },
        {
            id: "mutual05",
            type: "Mutual Fund",
            name: "GRO4US Fund",
            description: "Powerhouse market drives strong fund's price up to record high",
            rule: "Only you may buy as many units as you want at this price. Everyone may sell at this price",
            symbol: "GRO4US",
            price: 40,
            range: "$10 to $30",
            dividend: false,
            id: "gro4us40",
            shares: 0
        },
        {
            id: "stock001",
            type: "Stock",
            name: "MYT4U Electronics Co.",
            description: "Booming market leads to record share price of this home electronics seller!",
            rule: "Only you may buy as many shares as you want at this price. Everyone may sell at this price.",
            symbol: "MYT4U",
            price: 40,
            range: "$5 to $30",
            dividend: false,
            id: "myt4u40",
            shares: 0
        },
        {
            id: "stock002",
            type: "Stock",
            name: "MYT4U Electronics Co.",
            description: "High inflation leads to poor share price for this home electronics seller.",
            rule: "Only you may buy as many shares as you want at this price. Everyone may sell at this price.",
            symbol: "MYT4U",
            price: 5,
            range: "$5 to $30",
            dividend: false,
            id: "myt4u05",
            shares: 0
        },
        {
            id: "stock003",
            type: "Stock",
            name: "MYT4U Electronics Co.",
            description: "Record interest rates lead to substandard share price for this home electronics seller",
            rule: "Only you may buy as many shares as you want at this price. Everyone may sell at this price.",
            symbol: "MYT4U",
            price: 5,
            range: "$5 to $30",
            dividend: false,
            id: "myt4u05",
            shares: 0
        },
        {
            id: "stock004",
            type: "Stock",
            name: "MYT4U Electronics Co.",
            description: "Strong market leads to strong share price for this home electronics seller",
            rule: "Only you may buy as many shares as you want at this price. Everyone may sell at this price.",
            symbol: "MYT4U",
            price: 30,
            range: "$5 to $30",
            dividend: false,
            id: "myt4u30",
            shares: 0
        },
        {
            id: "stock005",
            type: "Stock",
            name: "MYT4U Electronics Co.",
            description: "Trade war panic leads to record low share price for this home electronics seller.",
            rule: "Only you may buy as many shares as you want at this price. Everyone may sell at this price.",
            symbol: "MYT4U",
            price: 1,
            range: "$5 to $30",
            dividend: false,
            id: "myt4u01",
            shares: 0
        },
        {
            id: "stock006",
            type: "Stock",
            name: "MYT4U Electronics Co.",
            description: "Weak market leads to sagging share price for this home electronics seller.",
            rule: "Only you may buy as many shares as you want at this price. Everyone may sell at this price.",
            symbol: "MYT4U",
            price: 10,
            range: "$5 to $30",
            dividend: false,
            id: "myt4u10",
            shares: 0
        },
        {
            id: "stock007",
            type: "Stock",
            name: "MYT4U Electronics Co.",
            description: "Fast growing seller of home electronics headed by 32 year old Harvard grad.",
            rule: "Only you may buy as many shares as you want at this price. Everyone may sell at this price.",
            symbol: "MYT4U",
            price: 20,
            range: "$5 to $30",
            dividend: false,
            id: "myt4u20",
            shares: 0
        },
        {
            id: "stock008",
            type: "Stock",
            name: "MYT4U Electronics Co.",
            description: "Low interest rates lead to substantial share price for this home electronics seller.",
            rule: "Only you may buy as many shares as you want at this price. Everyone may sell at this price.",
            symbol: "MYT4U",
            price: 30,
            range: "$5 to $30",
            dividend: false,
            id: "myt4u30",
            shares: 0
        },
        {
            id: "stock009",
            type: "Stock",
            name: "OK4U Drug Co.",
            description: "Market strength leads to high share price for this long time maker of medicines.",
            rule: "Only you may buy as many shares as you want at this price. Everyone may sell at this price.",
            symbol: "OK4U",
            price: 40,
            range: "$5 to $40",
            dividend: false,
            id: "ok4u10",
            shares: 0
        },
        {
            id: "stock010",
            type: "Stock",
            name: "OK4U Drug Co.",
            description: "Low inflation leads to high share price for this long time maker of medicines.",
            rule: "Only you may buy as many shares as you want at this price. Everyone may sell at this price.",
            symbol: "OK4U",
            price: 20,
            range: "$5 to $40",
            dividend: false,
            id: "ok4u20",
            shares: 0
        },
        {
            id: "stock011",
            type: "Stock",
            name: "OK4U Drug Co.",
            description: "Booming market raises share price of this long time maker of medicines.",
            rule: "Only you may buy as many shares as you want at this price. Everyone may sell at this price.",
            symbol: "OK4U",
            price: 50,
            range: "$5 to $40",
            dividend: false,
            id: "ok4u50",
            shares: 0
        },
        {
            id: "stock012",
            type: "Stock",
            name: "OK4U Drug Co.",
            description: "Interest rates cripple share price of this long time maker of medicines.",
            rule: "Only you may buy as many shares as you want at this price. Everyone may sell at this price.",
            symbol: "OK4U",
            price: 5,
            range: "$5 to $40",
            dividend: false,
            id: "ok4u05",
            shares: 0
        },
        {
            id: "stock013",
            type: "Stock",
            name: "OK4U Drug Co.",
            description: "High interest rates cause poor share price of this long time make of medicines.",
            rule: "Only you may buy as many shares as you want at this price. Everyone may sell at this price.",
            symbol: "OK4U",
            price: 10,
            range: "$5 to $40",
            dividend: false,
            id: "ok4u10",
            shares: 0
        },
        {
            id: "stock014",
            type: "Stock",
            name: "OK4U Drug Co.",
            description: "Inflation worries cause poor share price of this long time maker of medicines.",
            rule: "Only you may buy as many shares as you want at this price. Everyone may sell at this price.",
            symbol: "OK4U",
            price: 10,
            range: "$5 to $40",
            dividend: false,
            id: "ok4u10",
            shares: 0
        },
        {
            id: "stock015",
            type: "Stock",
            name: "OK4U Drug Co.",
            description: "Market panic causes crash in the shares of this long time maker of medicines.",
            rule: "Only you may buy as many shares as you want at this price. Everyone may sell at this price.",
            symbol: "OK4U",
            price: 1,
            range: "$5 to $40",
            dividend: false,
            id: "ok4u01",
            shares: 0
        },
        {
            id: "stock016",
            type: "Stock",
            name: "OK4U Drug Co.",
            description: "Long time maker of medicines; especially drugs for people of 70.",
            rule: "Only you may buy as many shares as you want at this price. Everyone may sell at this price.",
            symbol: "OK4U",
            price: 30,
            range: "$5 to $40",
            dividend: false,
            id: "ok4u30",
            shares: 0
        },
        {
            id: "stock021",
            type: "Stock",
            name: "ON2U Entertainment Co.",
            description: "Box office hit by children's division casuses record share price.",
            rule: "Only you may buy as many shares as you want at this price. Everyone may sell at this price.",
            symbol: "ON2U",
            price: 40,
            range: "$5 to $40",
            dividend: false,
            id: "on2u40",
            shares: 0
        },
        {
            id: "stock022",
            type: "Stock",
            name: "ON2U Entertainment Co.",
            description: "Strong demand for company's library of old movies on video leads to good share price.",
            rule: "Only you may buy as many shares as you want at this price. Everyone may sell at this price.",
            symbol: "ON2U",
            price: 30,
            range: "$5 to $40",
            dividend: false,
            id: "on2u30",
            shares: 0
        },
        {
            id: "stock023",
            type: "Stock",
            name: "ON2U Entertainment Co.",
            description: "New director of movie acquisitions brings revived prospects for share price.",
            rule: "Only you may buy as many shares as you want at this price. Everyone may sell at this price.",
            symbol: "ON2U",
            price: 20,
            range: "$5 to $40",
            dividend: false,
            id: "on2u20",
            shares: 0
        },
        {
            id: "stock024",
            type: "Stock",
            name: "ON2U Entertainment Co.",
            description: "Movie buyer fired after third mega-flop! Shares sink. Chairman's bonus canceled.",
            rule: "Only you may buy as many shares as you want at this price. Everyone may sell at this price.",
            symbol: "ON2U",
            price: 5,
            range: "$5 to $40",
            dividend: false,
            id: "on2u05",
            shares: 0
        },
        {
            id: "stock025",
            type: "Stock",
            name: "ON2U Entertainment Co.",
            description: "Box office smash hit in adult division causes strong share price.",
            rule: "Only you may buy as many shares as you want at this price. Everyone may sell at this price.",
            symbol: "ON2U",
            price: 30,
            range: "$5 to $40",
            dividend: false,
            id: "on2u30",
            shares: 0
        },
        {
            id: "stock026",
            type: "Stock",
            name: "ON2U Entertainment Co.",
            description: "Recent merger strengthened market share of this leading company with good outlook.",
            rule: "Only you may buy as many shares as you want at this price. Everyone may sell at this price.",
            symbol: "ON2U",
            price: 20,
            range: "$5 to $40",
            dividend: false,
            id: "on2u20",
            shares: 0
        },
        {
            id: "stock027",
            type: "Stock",
            name: "ON2U Entertainment Co.",
            description: "Newest theme park loses record amount. Share price hits all-time low.",
            rule: "Only you may buy as many shares as you want at this price. Everyone may sell at this price.",
            symbol: "ON2U",
            price: 1,
            range: "$5 to $40",
            dividend: false,
            id: "on2u01",
            shares: 0
        },
        {
            id: "stock028",
            type: "Stock",
            name: "ON2U Entertainment Co.",
            description: "Box office flop by musical extravaganza in core division causes poor share price.",
            rule: "Only you may buy as many shares as you want at this price. Everyone may sell at this price.",
            symbol: "ON2U",
            price: 10,
            range: "$5 to $40",
            dividend: false,
            id: "on2u10",
            shares: 0
        },
        {
            id: "stockSplit1",
            type: "Stock Split",
            name: "MYT4U Electronics Co.",
            description: "Business is up dramatically and the company is doing so well their shares haave just split!",
            rule: "Everyone who owns MYT4U shares doubles the number of shares they own.",
            symbol: "MYT4U"
        },
        {
            id: "stockSplit2",
            type: "Reverse Split",
            name: "MYT4U Electronics Co.",
            description: "Company reorganizes! Massive loses due to over expansion and recession. Stockholders lose 1/2 of their ownership rights.",
            rule: "Everyone who owns MYT4U shares cuts shares owned to 1/2 previous value.",
            symbol: "MYT4U"
        },
        {
            id: "stockSplit3",
            type: "Stock Split",
            name: "OK4U Drug Co.",
            description: "Things are going so well for the company that their shares have just split!",
            rule: "Everyone who owns OK4U shares doubles the number of shares they own.",
            symbol: "OK4U"
        },
        {
            id: "stockSplit4",
            type: "Reverse Split",
            name: "OK4U Drug Co.",
            description: "Company flounders! Massive losses due to tainted drug scandal. All stockholders lose 1/2 of their ownership rights.",
            rule: "Everyone who owns OK4U shares cuts shares owned to 1/2 previous value.",
            symbol: "OK4U"
        },
        {
            id: "preferredStock1",
            type: "Preferred Stock",
            name: "2BIG Power",
            description: "High yield, preferred shares of major domestic electric power company. Dividend and price fixed at \"fair\" level by state utility commission.",
            rule: "Everyone may buy or sell as many shares as they wish at this time.",
            symbol: "2BIG",
            dividend: 30,
            price: 1200,
            tradingRange: "$1,200 to $1,200",
            id: "2big",
            shares: 0
        },
        {
            id: "preferredStock2",
            type: "Preferred Stock",
            name: "1GLOBE Oil",
            description: "Moderate yield, preferred shares of major international biotech company. Dividend and price fixed at \"fair\" level by state utility commission.",
            rule: "Everyone may buy or sell as many shares as they wish at this time.",
            symbol: "1GLO",
            dividend: 15,
            price: 1000,
            tradingRange: "$1,200 to $1,200",
            id: "1globe",
            shares: 0
        },
        {
            id:"realEstateS1",
            type: "Real Estate",
            name: "You Find a Great Deal!",
            description: "Older 3/2 house, repossessed by government agency. Ready to go with government financing and a tenant.",
            rule: "Borrow from the Bank if you must, but... BUY THIS! 132% ROI, may sell for $65,000 to $135,000.",
            roi: 1.32,
            cost: 35000,
            downPayment: 2000,
            mortgage: 33000,
            cashFlow: 220,
            tag: "3Br/2Ba",
            landType: "3Br/2Ba"
        },
        {
            id:"realEstateS2",
            type: "Real Estate",
            name: "Condo for Sale - 2 Br/1 Ba",
            description: "Nice 2/1 condo available due to marriage of owner. Bad area. Needs work.",
            rule: "Use this yourself or sell to another player. 24% ROI, may sell for $45,000 to $65,000.",
            roi: 0.24,
            cost: 50000,
            downPayment: 5000,
            mortgage: 45000,
            cashFlow: 100,
            tag: "2Br/1Ba",
            landType: "2Br/1Ba"
        },
        {
            id:"realEstateS3",
            type: "Real Estate",
            name: "Condo For Sale - 2 Br/1 Ba",
            description: "Parents selling 2/1 condo used by their chil in college town. Lots of demand for rentals in this area.",
            rule: "Use this yourself or sell to another player. 42% ROI, may sell for $45,000 to $65,000.",
            roi: 0.42,
            cost: 40000,
            downPayment: 4000,
            mortgage: 36000,
            cashFlow: 140,
            tag: "2Br/1Ba",
            landType: "2Br/1Ba"
        },
        {
            id:"realEstateS4",
            name: "Condo For Sale - 2 Br/1 Ba",
            type: "Real Estate",
            description: "Older 2/1 condo offered by young couple who want to move up to a 3/2 house due to growing family. Available soon.",
            rule: "Use this yourself or sell to another player. 38% ROI, may sell for $45,000 to $65,000.",
            roi: 0.38,
            cost: 50000,
            downPayment: 5000,
            mortgage: 45000,
            cashFlow: 100,
            tag: "2Br/1Ba",
            landType: "2Br/1Ba"
        },
        {
            id:"realEstateS5",
            name: "Condo For Sale - 2 Br/1 Ba",
            type: "Real Estate",
            description: "Excellent 2/1 condo with many extras. For sale due to business success of owner. She's moving up, so can you.",
            rule: "Use this yourself or sell to another player. -24% ROI, may sell for $45,000 to $65,000.",
            roi: -0.24,
            cost: 60000,
            downPayment: 5000,
            mortgage: 55000,
            cashFlow: -100,
            tag: "2Br/1Ba",
            landType: "2Br/1Ba"
        },
        {
            id:"realEstateS6",
            name: "Condo For Sale - 2 Br/1 Ba",
            type: "Real Estate",
            description: "Bank foreclosure! 2/1 condo in desirable neighborhood close to jobs and stores. Make offer, favorable financing by bank.",
            rule: "Use this yourself or sell to another player. 53% ROI, may sell for $45,000 to $65,000",
            roi: 0.53,
            cost: 40000,
            downPayment: 5000,
            mortgage: 35000,
            cashFlow: 220,
            tag: "2Br/1Ba",
            landType: "2Br/1Ba"
        },
        {
            id:"realEstateS7",
            name: "House For Sale - 3 Br/2 Ba",
            type: "Real Estate",
            description: "Not lived in for 6 months, this bank-foreclosed house just reduced. Loan includes estimated repair costs.",
            rule: "Use this yourself or sell to another player. May sell for $65,000 to $135,000.",
            roi: 0,
            cost: 50000,
            downPayment: 0,
            mortgage: 50000,
            cashFlow: 100,
            tag: "3Br/2Ba",
            landType: "3Br/2Ba"
        },
        {
            id:"realEstateS8",
            name: "House For Sale - 3 Br/2 Ba",
            type: "Real Estate",
            description: "Low down payment to pick up this 3/2 house. Owner/seller unexpectedly moving out of town. Right person will do well.",
            rule: "Use this yourself or sell to another player. 40% ROI, may sell for $65,000 to $135,000.",
            roi: 0.4,
            cost: 50000,
            downPayment: 3000,
            mortgage: 47000,
            cashFlow: 100,
            tag: "3Br/2Ba",
            landType: "3Br/2Ba"
        },
        {
            id:"realEstateS9",
            name: "House For Sale - 3 Br/2 Ba",
            type: "Real Estate",
            description: "3/2 house in older area offered by Highway Department. Market has crashed. No bids at last week's auction.",
            rule: "Use this yourself or sell to another player. ??% ROI, may sell for $65,000 to $135,000.",
            cost: 50000,
            downPayment: 0,
            mortgage: 50000,
            cashFlow: -100,
            tag: "3Br/2Ba",
            landType: "3Br/2Ba"
        },
        {
            id:"realEstateS10",
            name: "House For Sale - 3 Br/2 Ba",
            type: "Real Estate",
            description: "Nice 3/2 rental house suddenly available due to estate closing. Well maintained older property with existing tenant.",
            rule: "Use this yourself or sell to another player. 38% ROI, may sell for $65,000 to $135,000.",
            roi: 0.38,
            cost: 65000,
            downPayment: 5000,
            mortgage: 60000,
            cashFlow: 160,
            tag: "3Br/2Ba",
            landType: "3Br/2Ba"
        },
        {
            id:"realEstateS11",
            name: "House For Sale - 3 Br/2 Ba",
            type: "Real Estate",
            description: "Nice 3/2 house available in depressed market due to layoffs. Would make good investment property for right buyer.",
            rule: "Use this yourself or sell to another player. 60% ROI, may sell for $65,000 to $135,000.",
            roi: 0.6,
            cost: 50000,
            downPayment: 4000,
            mortgage: 46000,
            cashFlow: 200,
            tag: "3Br/2Ba",
            landType: "3Br/2Ba"
        },
        {
            id:"realEstateS12",
            name: "You Find a Great Deal!",
            type: "Real Estate",
            description: "Company bought transferred manager's 3/2 house. No current tenant, has been on market 6 months, just reduced.",
            rule: "Borrow from the Bank if you must, but... BUY THIS! 150% ROI, may sell for $65,000 to $135,000.",
            roi: 1.5,
            cost: 50000,
            downPayment: 4000,
            mortgage: 46000,
            cashFlow: 200,
            tag: "3Br/2Ba",
            landType: "3Br/2Ba"
        },
        {
            id:"realEstateS13",
            name: "10 Acres Raw Land",
            type: "Real Estate",
            description: "Wonderful park-like setting with stream on 10 acres in undeveloped area. No roads, no utilities, no noise.",
            rule: "Use this yourself or sell to another player. 0% ROI, possible future sale at ??.",
            roi: 0,
            cost: 5000,
            downPayment: 5000,
            mortgage: 0,
            cashFlow: 0,
            tag: "10 acres",
            landType: "10 acres"
        },
        {
            id: "propertyDamage", 
            name: "Tenant Damages Your Property",
            type: "Property Damage",
            description: "Tenant fails to pay rent for 2 months and then skips town leaving damage to your rental property. Insurance covers most damage and costs, but you are still out of pocket $500.",
            rule: "Pay $500 if you own any rental property",
            propertyType: "rental",
            landType: "rental",
            cost: 500
        },
        {
            id:"coin1",
            type: "Coin",
            name: "1500's Spanish",
            title: "Rare Gold Coin",
            description: "You spot an unusual 1500's Royal Spanish New World (Havana Mint Only) \"pieces of eight\" gold coin in good condition at a swap meet. One only, seller asks $500.",
            rule: "Use this yourself or sell to another player. 0% ROI, may sell for $0 to $4,000.",
            roi: 0,
            cost: 500,
            downPayment: 500,
            liability: 0,
            cashFlow: 0,
            amount: 1
        },
        {
            id:"coin2",
            type: "Coin",
            name: "Krugerrands",
            title: "Friend Needs Cash... Quick",
            description: "A friend has urgent need for money. Will sell you 10 one-ounce gold Krugerrands, well below going rate, for $300 each.",
            rule: "Use this yourself or sell to another player. 0% ROI, possible future sale at ??",
            roi: 0,
            cost: 3000,
            downPayment: 3000,
            liability: 0,
            cashFlow: 0,
            amount: 10
        },
        {
          id: "cd1",
          type: "Certificate of Deposit",
          name: "Certificate of Deposit 1",
          description: "A leading bank offers this special Certificate of Deposit to its customer. Guaranteed interest and redeemable after any holding period.",
          rule: "Everyone may buy or sell as many as they wish at this time.",
          symbol: "CD-A",
          dividend: 12,
          price: 500,
          range: "$5,000 to $5,000",
		  id: "cd1",
		  shares: 0
        },
        {
          id: "cd2",
          type: "Certificate of Deposit",
          name: "Certificate of Deposit 2",
          description: "A leading bank offers this special Certificate of Deposit to its customer. Guaranteed interest and redeemable after any holding period.",
          rule: "Everyone may buy or sell as many as they wish at this time.",
          symbol: "CD-B",
          dividend: 60,
          price: 2000,
          range: "$5,000 to $5,000",
		  id: "cd2",
		  shares: 0
        },
        {
            id:"companyS1",
            type: "Company",
            name: "Start a Company Part Time",
            description: "Develop interesting idea for a software program, so you start a company to produce and sell it. No profits during startup, long hours, no extra pay.",
            rule: "Use this yourself or sell to another player. 0% ROI, may sell for ??, if anything.",
            roi: 0,
            cost: 5000,
            downPayment: 5000,
            liability: 0,
            cashFlow: 0,
            tag: "SOFTWARE",
            landType: "business",
            businessType: "software"
        },
        {
            id:"companyS2",
            type: "Company",
            name: "Start a Company Part Time",
            description: "Invent new way of making widgets, so you start a company to produce and sell them. No profits during startup, long hourse, no extra pay.",
            rule: "Use this yourself or sell to another player. 0% ROI, may sell for ??, if anything.",
            roi: 0,
            cost: 3000,
            downPayment: 3000,
            liability: 0,
            cashFlow: 0,
            tag: "WIDGET",
            landType: "business",
            businessType: "widget"
        }
]
